# Copyright (c) 2021, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if eq .Values.type "NGINX" }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-nginx
  namespace: {{ .Release.Namespace }}

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: persistent
{{- if eq .Values.tls "SSL" }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_input_headers "X-Forwarded-Proto: https";
      more_set_input_headers "WL-Proxy-SSL: true";
    nginx.ingress.kubernetes.io/ingress.allow-http: "false"
{{- end }}
spec:
  rules:
  - host: '{{ .Values.nginx.hostname }}'
    http:
      paths:
      - path: /console
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /em
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /wls-exporter
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /cs
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /adfAuthentication
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /_ocsh
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /_dav
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /idcws
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /idcnativews
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /wsm-pm
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /ibr
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ibrClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ibrManagedServerPort }}
      - path: /ibr/adfAuthentication
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ibrClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ibrManagedServerPort }}
      - path: /weblogic/ready
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /imaging
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ipmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ipmManagedServerPort }}
      - path: /dc-console
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.captureClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.captureManagedServerPort }}
      - path: /dc-client
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.captureClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.captureManagedServerPort }}
      - path: /wcc
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.wccadfClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.wccadfManagedServerPort }}

{{- if eq .Values.tls "SSL" }}
  tls:
  - hosts:
    - '{{ .Values.nginx.hostname }}'
    secretName: domain1-tls-cert
{{- end }}

{{- end }}

