# Copyright (c) 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if eq .Values.type "VOYAGER" }}
---
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-voyager
  namespace: {{ .Release.Namespace }}
  #namespace: wccns
  labels:
    weblogic.resourceVersion: domain-v2
  annotations:
    ingress.appscode.com/type: 'NodePort'
    ingress.appscode.com/stats: 'true'
    ingress.appscode.com/affinity: 'cookie'
spec:
{{- if eq .Values.tls "SSL" }}
  frontendRules:
  - port: 443
    rules:
    - http-request set-header WL-Proxy-SSL true
  tls:
  - secretName: domain1-tls-cert
    hosts:
    - '*'
{{- end }}
  rules:
  - host: '*'
    http:
      nodePort: '{{ .Values.voyager.webPort }}'
      paths:
      - path: /console
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /em
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /wls-exporter
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /cs
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /adfAuthentication
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /_ocsh
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /_dav
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /idcws
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /idcnativews
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /wsm-pm
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /ibr
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ibrClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ibrManagedServerPort }}
      - path: /ibr/adfAuthentication
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ibrClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ibrManagedServerPort }}
      - path: /weblogic/ready
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.ucmManagedServerPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-voyager-stats
  namespace: {{ .Release.Namespace }}
  labels:
    weblogic.resourceVersion: domain-v2
spec:
  type: NodePort
  ports:
    - name: client
      protocol: TCP
      port: 56789
      targetPort: 56789
      nodePort: {{ .Values.voyager.statsPort }}
  selector:
    origin: voyager
    origin-name: {{ .Values.wlsDomain.domainUID }}-voyager
{{- end }}
