# Copyright (c) 2020, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# Default values for ingress-per-domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Load balancer type.  Supported values are: VOYAGER, NGINX
type: VOYAGER
# Type of Configuration Supported Values are : NONSSL,SSL
# tls: NONSSL
tls: SSL
# TLS secret name if the mode is SSL
secretName: domain1-tls-cert


# WLS domain as backend to the load balancer
wlsDomain:
  domainUID: oimcluster
  oimClusterName: oim_cluster
  soaClusterName: soa_cluster
  soaManagedServerPort: 8001
  oimManagedServerPort: 14000
  adminServerName: adminserver
  adminServerPort: 7001


# Voyager specific values
voyager:
  # web port
  webPort: 30305
  # stats port
  statsPort: 30315
