apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "oracledb-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "oracledb-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ include "oracledb-operator.namespace" . }}
