apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "oracledb-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "oracledb-operator.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "oracledb-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ include "oracledb-operator.namespace" . }}
