apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: {{ include "oracledb-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ include "oracledb-operator.namespace" . }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
