# Source: oud-ds-rs/templates/elk_logstash-configMap.yaml
#
# Copyright (c) 2025, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl
#
#
apiVersion: v1
kind: ConfigMap
metadata:
 name: oudsm-logstash-configmap
 namespace: <OUDSMNS>
data:
 logstash.yaml: |
 #http.host: "0.0.0.0"
 logstash-config.conf: |
   input {
      file {
        path => "/u01/oracle/user_projects/domains/oudsmdomain-1/servers/AdminServer/logs/*.log"
        type => "setup-logs"
        start_position => beginning
        sincedb_path => "/dev/null"
      }
    }
    filter {
      if [type] == "setup-logs" {
        grok {
          match => [ "message", "<%{DATA:log_timestamp}> <%{WORD:log_level}> <%{WORD:thread}> <%{HOSTNAME:hostname}> <%{HOSTNAME:hostserver}> %{GREEDYDATA:message}" ]
          }
      }
      if "_grokparsefailure" in [tags] {
        mutate {
          remove_tag => [ "_grokparsefailure" ]
          }
        }
      }
   output {
    elasticsearch {
      hosts => ["<ELK_HOST>"]
      cacert => '/usr/share/logstash/config/certs/elk.crt'
      user => "<ELK_USER>"
      password => "<ELK_USER_PWD>"
      index => "oudsmlogs-000001"
      ssl => true
      ssl_certificate_verification => false
    }
   }
