# Copyright (c) 2021, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl

apiVersion: batch/v1
kind: Job
metadata:
  name: %DOMAIN_UID%-delete-fmw-infra-sample-domain-job
  namespace: %NAMESPACE%
spec:
  template:
    metadata:
      labels:
        weblogic.resourceVersion: domain-v2
        weblogic.domainUID: %DOMAIN_UID%
        weblogic.domainName: %DOMAIN_NAME%
        app: %DOMAIN_UID%-delete-fmw-infra-sample-domain-job
    spec:
      restartPolicy: Never
      containers:
        - name: delete-fmw-infra-sample-domain-job
          image: %WEBLOGIC_IMAGE%
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7001
          volumeMounts:
          - mountPath: %CREATE_DOMAIN_SCRIPT_DIR%
            name: create-fmw-infra-sample-domain-job-cm-volume
          - mountPath: %DOMAIN_ROOT_DIR%
            name: fmw-infra-sample-domain-storage-volume
          - mountPath: /weblogic-operator/rcu-secrets
            name: rcu-credentials-volume
          command: ["/bin/sh"]
          args: ["%CREATE_DOMAIN_SCRIPT_DIR%/drop-rcu-schema.sh"]
          env:
            - name: DOMAIN_HOME_DIR
              value: %DOMAIN_HOME%
            - name: DOMAIN_LOGS_DIR
              value: %DOMAIN_ROOT_DIR%/logs/%DOMAIN_UID%
            - name: CUSTOM_RCUPREFIX
              value: "%CUSTOM_RCUPREFIX%"
            - name: CUSTOM_CONNECTION_STRING
              value: "%CUSTOM_CONNECTION_STRING%"
            - name: CREATE_DOMAIN_SCRIPT_DIR
              value: "%CREATE_DOMAIN_SCRIPT_DIR%"

      volumes:
        - name: create-fmw-infra-sample-domain-job-cm-volume
          configMap:
            name: %DOMAIN_UID%-create-fmw-infra-sample-domain-job-cm
        - name: fmw-infra-sample-domain-storage-volume
          persistentVolumeClaim:
            claimName: %DOMAIN_PVC_NAME%
        - name: rcu-credentials-volume
          secret:
            secretName: %RCU_CREDENTIALS_SECRET_NAME%
      %WEBLOGIC_IMAGE_PULL_SECRET_PREFIX%imagePullSecrets:
      %WEBLOGIC_IMAGE_PULL_SECRET_PREFIX%- name: %WEBLOGIC_IMAGE_PULL_SECRET_NAME%
