# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
{{- if eq .Values.type "NGINX" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-nginx-designconsole
  namespace: {{ .Release.Namespace }}
  labels:
    weblogic.resourceVersion: domain-v2
  annotations:
    nginx.ingress.kubernetes.io/affinity: 'cookie'
    nginx.ingress.kubernetes.io/enable-access-log: 'false'
    kubernetes.io/ingress.class: 'nginx'
{{- if eq .Values.tls "SSL" }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: '2000k'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_input_headers "X-Forwarded-Proto: https";
      more_set_input_headers "WL-Proxy-SSL: true";
    nginx.ingress.kubernetes.io/ingress.allow-http: 'false'
{{- end }}
spec:
 rules:
   - http:
       paths:
       - path:
         pathType: ImplementationSpecific
         backend:
           service:
              name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
              port: 
                number: {{ .Values.wlsDomain.oimServerT3Port }}
{{- end }}
{{- end }}

