# Copyright (c) 2021, 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
#
# Default values for ingress-per-domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#

# Load balancer type. Supported values are: TRAEFIK,NGINX
type: TRAEFIK

# SSL configuration Type. Supported Values are : NONSSL,SSL,E2ESSL
sslType: NONSSL


#WLS domain as backend to the load balancer
wlsDomain:
  domainUID: wccinfra
  secureEnabled: false
  adminServerName: adminserver
  adminSecurePort: 9002
  adminServerPort: 7001
  adminServerSSLPort: 7002
  ibrClusterName: ibr_cluster
  ibrManagedServerPort: 16250
  ibrManagedServerSSLPort: 16251
  ucmClusterName: ucm_cluster
  ucmManagedServerPort: 16200
  ucmManagedServerSSLPort: 16201
  ipmClusterName: ipm_cluster
  ipmManagedServerPort: 16000
  ipmManagedServerSSLPort: 16001
  captureClusterName: capture_cluster
  captureManagedServerPort: 16400
  captureManagedServerSSLPort: 16401
  wccadfClusterName: wccadf_cluster
  wccadfManagedServerPort: 16225
  wccadfManagedServerSSLPort: 16226
  ipmEnabled: false
  captureEnabled: false
  adfuiEnabled: false

# Host  specific values
hostName:
  admin: admin.domain.org
  ucm: ucm.domain.org
  ibr: ibr.domain.org
  ipm: ipm.domain.org
  capture: capture.domain.org
  wccadf: wccadf.domain.org
 



