# Copyright (c) 2020, 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
#
# Default values for ingress-per-domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#

# Load balancer type. Supported values are: TRAEFIK,NGINX
type: TRAEFIK

# SSL configuration Type. Supported Values are : NONSSL,SSL,E2ESSL
sslType: NONSSL

# domainType. Supported values are: wcp,wcpp
domainType: wcp

#WLS domain as backend to the load balancer
wlsDomain:
  domainUID: wcp-domain
  secureEnabled: false
  adminServerName: AdminServer
  adminSecurePort: 9002
  adminServerPort: 7001
  adminServerSSLPort: 7002
  wcpClusterName: wcp-cluster
  wcpManagedServerPort: 8888
  wcpManagedServerSSLPort: 8788
  wcpPortletClusterName: wcpPortlet-cluster
  wcpPortletManagedServerPort: 8889
  wcpPortletManagedServerSSLPort: 8789

# Host  specific values
traefik:
  hostname: domain1.org

# Host  specific values
hostName:
  admin: admin.domain.org
  wcp: wcp.domain.org
  wcpportlet: wcpportlet.domain.org
 

# Ngnix specific values
nginx:
  connectTimeout: 1800
  readTimeout: 1800
  sendTimeout: 1800
  cookieExpires: 172800
  cookieMaxAge: 172800


