# Copyright (c) 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# This is an example file to setup a Persistent Volume for OIG DR
#
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: <ROLE>-oig-pv
  labels:
    type: <ROLE>-oig-pv
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: <OIG_SHARE_PATH>
    server: <PVSERVER>
