# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
{{- if (eq .Values.sslType "SSL") }}
{{ if not .Values.tls.secretName }}
---
{{- $ca := genCA .Values.tls.certCommonName (int .Values.tls.validityDays) }}

{{- $soatlscert := genSignedCert .Values.tls.certCommonName nil (list .Values.tls.certCommonName) (int .Values.tls.validityDays) $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-tls-cert
  labels:
{{ include "common.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $soatlscert.Cert | b64enc | quote }}
  tls.key: {{ $soatlscert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}
{{- end }}
