#
# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
{{- if .Values.serviceAccount.create }}
---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- else -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "oudsm.fullname" . }}-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "oudsm.fullname" . }}-cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "oudsm.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
