# Copyright (c) 2020, 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
#
# Default values for ingress-per-domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#

# Load balancer type. Supported values are: TRAEFIK,NGINX
type: TRAEFIK

# SSL configuration Type. Supported Values are : NONSSL,SSL,E2ESSL
sslType: NONSSL

# domainType. Supported values are: wcs
domainType: wcs

#WLS domain as backend to the load balancer
wlsDomain:
  domainUID: wcsitesinfra
  secureEnabled: false
  adminServerName: adminserver
  adminSecurePort: 9002
  adminServerPort: 7001
  adminServerSSLPort: 7002
  wcsitesClusterName: wcsites-cluster
  wcsitesManagedServerPort: 7103
  wcsitesManagedServerSSLPort: 7104

# Host  specific values
hostName:
  admin: admin.domain.org
  wcs: wcsites.domain.org
 

# Ngnix specific values
nginx:
  connectTimeout: 1800
  readTimeout: 1800
  sendTimeout: 1800
  cookieExpires: 172800
  cookieMaxAge: 172800


