# Copyright (c) 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if eq .Values.type "TRAEFIK" }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-traefik
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
{{- if eq .Values.tls "SSL" }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: wcpns-wls-proxy-ssl@kubernetescrd
{{- end }}
spec:
  rules:
  - host: '{{ .Values.traefik.hostname }}'
    http:
      paths:
      - path: /webcenter
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.clusterName | lower}}'
          servicePort: {{.Values.wlsDomain.managedServerPort}}
      - path: /console
        backend:
          serviceName: '{{.Values.wlsDomain.domainUID}}-{{.Values.wlsDomain.adminServerName| lower}}'
          servicePort: {{.Values.wlsDomain.adminServerPort}}
      - path: /rsscrawl
        backend:
          serviceName: '{{.Values.wlsDomain.domainUID}}-cluster-{{.Values.wlsDomain.clusterName | lower}}'
          servicePort: {{.Values.wlsDomain.managedServerPort}}
      - path: /webcenterhelp
        backend:
          serviceName: '{{.Values.wlsDomain.domainUID}}-cluster-{{.Values.wlsDomain.clusterName | lower}}'
          servicePort: {{.Values.wlsDomain.managedServerPort}}
      - path: /rest
        backend:
          serviceName: '{{.Values.wlsDomain.domainUID}}-cluster-{{.Values.wlsDomain.clusterName | lower}}'
          servicePort: {{.Values.wlsDomain.managedServerPort}}
      - path: /em
        backend:
          serviceName: '{{.Values.wlsDomain.domainUID}}-{{.Values.wlsDomain.adminServerName| lower}}'
          servicePort: {{.Values.wlsDomain.adminServerPort}}

  {{- if eq .Values.tls "SSL" }}
  tls:
  - hosts:
    - '{{ .Values.traefik.hostname }}'
    secretName: wcpinfra-tls-cert
{{- end }}
{{- end }}
