# Copyright (c) 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# This is an example file to setup a Persistent Volume Claim for OAA DR
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <ROLE>-oaa-config-pvc
  namespace: <DRNS>
  labels:
    type: <ROLE>-oaa-config-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 30Gi
  selector:
    matchLabels:
      type: <ROLE>-oaa-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <ROLE>-oaa-vault-pvc
  namespace: <DRNS>
  labels:
    type: <ROLE>-oaa-vault-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 30Gi
  selector:
    matchLabels:
      type: <ROLE>-oaa-vault-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <ROLE>-oaa-cred-pvc
  namespace: <DRNS>
  labels:
    type: <ROLE>-oaa-cred-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 30Gi
  selector:
    matchLabels:
      type: <ROLE>-oaa-cred-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <ROLE>-oaa-log-pvc
  namespace: <DRNS>
  labels:
    type: <ROLE>-oaa-log-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 30Gi
  selector:
    matchLabels:
      type: <ROLE>-oaa-log-pv
