#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oudsm.fullname" . }}-lbr
  labels:
    {{- include "oudsm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.sslPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "oudsm.selectorLabels" . | nindent 4 }}
