# Copyright (c) 2020, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if eq .Values.type "VOYAGER" }}
---
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-voyager
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.appscode.com/type: 'NodePort'
    kubernetes.io/ingress.class: 'voyager'
    ingress.appscode.com/stats: 'true'
    ingress.appscode.com/default-timeout: '{"connect": "1800s", "server": "1800s"}'
    ingress.appscode.com/proxy-body-size: "2000000"
  labels:
    weblogic.resourceVersion: domain-v2
spec:
{{- if eq .Values.tls "SSL" }}
  frontendRules:
  - port: 443
    rules:
    - http-request set-header WL-Proxy-SSL true
  tls:
  - secretName: domain1-tls-cert
    hosts:
    - '*'
{{- end }}
  rules:
  - host: '*'
    http:
      nodePort: '{{ .Values.voyager.webPort }}'
      paths:
      - path: /console
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /rreg/rreg
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /em
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /oamconsole
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /dms
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /oam/services/rest
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /iam/admin/config
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /iam/admin/diag
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /iam/access
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oamClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oamManagedServerPort }}
      - path: /oam/admin/api
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.adminServerPort }}
      - path: /oam/services/rest/access/api
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oamClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oamManagedServerPort }}
      - path: /access
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.policyClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.policyServerPort }}
      - path: /
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oamClusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.oamManagedServerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-voyager-stats
  namespace: {{ .Release.Namespace }}
  labels:
    app: voyager-stats
spec:
  type: NodePort
  ports:
    - name: client
      protocol: TCP
      port: 56789
      targetPort: 56789
      nodePort: {{ .Values.voyager.statsPort }}
  selector:
    origin: voyager
    origin-name: {{ .Values.wlsDomain.domainUID }}-voyager
{{- end }}
