# Copyright (c) 2020, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# Default values for ingress-per-domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Load balancer type.  Supported values are: NGINX, VOYAGER

type: VOYAGER
# Type of Configuration Supported Values are : NONSSL,SSL
# tls: NONSSL
tls: SSL
# TLS secret name if the mode is SSL
secretName: domain1-tls-cert


# WLS domain as backend to the load balancer
wlsDomain:
  domainUID: accessinfra
  oamClusterName: oam_cluster
  policyClusterName: policy_cluster
  oamManagedServerPort: 14100
  policyServerPort: 15100
  adminServerName: adminserver
  adminServerPort: 7001
  Namespace: accessns

# Traefik specific values
#traefik:
  # hostname used by host-routing
  #hostname: xxxx.example.com

# Voyager specific values
voyager:
  # web port
  webPort: 30305
  # stats port
  statsPort: 30315

