#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl
#
#
{{- if and .Values.elkVolume.enabled (not .Values.elkVolume.pvname) }}
{{- $root := . -}}
{{- range $replicaIndex, $replicaN := until (.Values.elk.elasticsearch.esreplicas |int) }}
{{- $replicaIndx := (add $replicaIndex 1) -}}
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "oud-ds-rs.fullname" $root }}-espv{{ $replicaIndx }}
  labels:
    {{- include "oud-ds-rs.labels" $root | nindent 4 }}
spec:
  {{- if $root.Values.elkVolume.storageClass }}
  storageClassName: {{ $root.Values.elkVolume.storageClass }}
  {{- end }}
  capacity:
    storage: {{ $root.Values.elkVolume.size | quote }}
  accessModes:
    - {{ $root.Values.elkVolume.accessMode | quote }}
  {{- if (eq "networkstorage" $root.Values.elkVolume.type) }}
  nfs:
    path: {{ $root.Values.elkVolume.networkstorage.nfs.path }}{{ $replicaIndx }}
    server: {{ $root.Values.elkVolume.networkstorage.nfs.server }}
  {{- else if (eq "filesystem" $root.Values.elkVolume.type) }}
  hostPath:
    path: {{ $root.Values.elkVolume.filesystem.hostPath.path }}{{ $replicaIndx }}
  {{- else if (eq "custom" $root.Values.elkVolume.type) }}
    {{- with $root.Values.elkVolume.custom }}
    {{- toYaml . | nindent 2 }}
    {{- end }}
   {{- end }}
---
   {{- end }}
{{- end }}
