#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl
#
#
{{- if .Values.elk.elasticsearch.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "oud-ds-rs.fullname" . }}-es-cluster
spec:
  serviceName: {{ include "oud-ds-rs.fullname" . }}-elasticsearch
  replicas: {{ .Values.elk.elasticsearch.esreplicas }}
  selector:
    matchLabels:
      app: {{ include "oud-ds-rs.fullname" . }}-elasticsearch
  template:
    metadata:
      labels:
        app: {{ include "oud-ds-rs.fullname" . }}-elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: "{{ .Values.elk.elasticsearch.image.repository }}:{{ .Values.elk.elasticsearch.image.tag }}"
        resources:
{{ toYaml .Values.elk.elasticsearch.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.elk.elkPorts.rest }}
          name: rest
          protocol: TCP
        - containerPort: {{ .Values.elk.elkPorts.internode }}
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: {{ .Values.elkVolume.mountPath }}
        env:
          - name: cluster.name
            value: OUD-elk
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.zen.ping.unicast.hosts
            value: {{ include "es-discovery-hosts" .  | quote }}
            #value: "oud-ds-rs-es-cluster-0.oud-ds-rs-elasticsearch,oud-ds-rs-es-cluster-1.oud-ds-rs-elasticsearch,oud-ds-rs-es-cluster-2.oud-ds-rs-elasticsearch"
          - name: discovery.zen.minimum_master_nodes
            value: {{ .Values.elk.elasticsearch.minimumMasterNodes | quote }}
          - name: ES_JAVA_OPTS
            value: {{ .Values.elk.elasticsearch.esJAVAOpts | quote }}
      initContainers:
    {{- if (eq "filesystem" .Values.elkVolume.type) }}
      - name: fix-permissions
        image: {{ .Values.elk.busybox.image }}
        command: ["sh", "-c", "chown -R 1000:1000 {{ .Values.elkVolume.mountPath }}"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: {{ .Values.elkVolume.mountPath }}
    {{- end }}
      - name: increase-vm-max-map
        image: {{ .Values.elk.busybox.image }}
        command: ["sysctl", "-w", "vm.max_map_count={{ .Values.elk.elasticsearch.sysctlVmMaxMapCount }}"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: {{ .Values.elk.busybox.image }}
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
   - metadata:
       name: data
       labels:
         app: {{ include "oud-ds-rs.fullname" . }}-elasticsearch
     spec:
       accessModes: [ {{ .Values.elkVolume.accessMode | quote }} ]
       storageClassName: {{ .Values.elkVolume.storageClass }}
       resources:
         requests:
           storage: {{ .Values.elkVolume.size }}
{{- end }}
