#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "oud-ds-rs.fullname" . }}-0
  labels:
    {{- include "oud-ds-rs.labels" . | nindent 4 }}
    oud/instance: {{ include "oud-ds-rs.fullname" . }}-0
spec:
  restartPolicy: {{ .Values.restartPolicyName }}
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceAccountName: {{ include "oud-ds-rs.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  containers:
    - name: {{ .Chart.Name }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - name: adminldaps
          containerPort: {{ .Values.oudPorts.adminldaps }}
          protocol: TCP
        - name: adminhttps
          containerPort: {{ .Values.oudPorts.adminhttps }}
          protocol: TCP
        - name: ldap
          containerPort: {{ .Values.oudPorts.ldap }}
          protocol: TCP
        - name: ldaps
          containerPort: {{ .Values.oudPorts.ldaps }}
          protocol: TCP
        - name: http
          containerPort: {{ .Values.oudPorts.http }}
          protocol: TCP
        - name: https
          containerPort: {{ .Values.oudPorts.https }}
          protocol: TCP
        - name: replication
          containerPort: {{ .Values.oudPorts.replication }}
          protocol: TCP
      {{- if .Values.baseOUD.envVarsConfigMap }}
      envFrom:
      - configMapRef:
          name: {{ .Values.baseOUD.envVarsConfigMap }}
      {{- end }}
      env:
        {{- with .Values.baseOUD.envVars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: instanceType
          value: Directory
        - name: sleepBeforeConfig
          value: "3"
        - name: OUD_INSTANCE_NAME
          value: {{ include "oud-ds-rs.fullname" . }}-0
        - name: hostname
          value: {{ include "oud-ds-rs.fullname" . }}-0
        - name: baseDN
          value: {{ .Values.oudConfig.baseDN }}
        {{- if .Values.secret.enabled }}
        - name: rootUserDN
          valueFrom:
            secretKeyRef:
                {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              key: rootUserDN
                {{- else }}
              name:  {{ include "oud-ds-rs.fullname" . }}-creds
              key: rootUserDN
                {{- end }}
        {{- else }} 
        - name: rootUserDN
          value: {{ .Values.rootUserDN }}
        {{- end }}
        {{- if .Values.secret.enabled }}
        - name: rootUserPassword
          valueFrom:
            secretKeyRef:
              {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              key: rootUserPassword
              {{- else }}
              name:  {{ include "oud-ds-rs.fullname" . }}-creds
              key: rootUserPassword
              {{- end }}
        {{- else }}
        - name: rootUserPassword
          value: {{ .Values.rootUserPassword }}
        {{- end }}
        - name: adminConnectorPort
          value: {{ .Values.oudPorts.adminldaps | quote }}
        - name: httpAdminConnectorPort
          value: {{ .Values.oudPorts.adminhttps | quote }}
        - name: ldapPort
          value: {{ .Values.oudPorts.ldap | quote }}
        - name: ldapsPort
          value: {{ .Values.oudPorts.ldaps | quote }}
        - name: httpPort
          value: {{ .Values.oudPorts.http | quote }}
        - name: httpsPort
          value: {{ .Values.oudPorts.https | quote }}
        - name: replicationPort
          value: {{ .Values.oudPorts.replication | quote }}
        - name: sampleData
          value: {{ .Values.oudConfig.sampleData | quote }}
      volumeMounts:
        - mountPath: /u01/oracle/user_projects
        {{- if .Values.persistence.enabled }}
          {{- if .Values.persistence.pvname }}
          name: {{ .Values.persistence.pvname }}
          {{ else }}
          name: {{ include "oud-ds-rs.fullname" . }}-pv
          {{- end }}
        {{- else }}
          name: oud-storage
          subPath: user_projects
        {{- end }}
        {{- if .Values.configVolume.enabled }}
        - mountPath: {{ .Values.configVolume.mountPath }}
          {{- if .Values.configVolume.pvname }}
          name: {{ .Values.configVolume.pvname }}
          {{ else }}
          name: {{ include "oud-ds-rs.fullname" . }}-pv-config
          {{- end }}
        {{- end }}
      livenessProbe:
        tcpSocket:
          port: ldap
        initialDelaySeconds: {{ (.Values.deploymentConfig.livenessProbeInitialDelay|int) }}
        timeoutSeconds: 15
        periodSeconds: 30
        failureThreshold: 1
      readinessProbe:
        tcpSocket:
          port: ldap
        initialDelaySeconds: {{ (.Values.deploymentConfig.startupTime|int) }}
        timeoutSeconds: 15
        periodSeconds: 30
      readinessProbe:
        tcpSocket:
          port: adminldaps
        initialDelaySeconds: {{ (.Values.deploymentConfig.startupTime|int) }}
        timeoutSeconds: 15
        periodSeconds: 30
      readinessProbe:
        tcpSocket:
          port: http
        initialDelaySeconds: {{ (.Values.deploymentConfig.startupTime|int) }}
        timeoutSeconds: 15
        periodSeconds: 30
      readinessProbe:
        exec:
          command:
            - "/u01/oracle/container-scripts/checkOUDInstance.sh"
        initialDelaySeconds: {{ (.Values.deploymentConfig.startupTime|int) }}
        timeoutSeconds: 30
        periodSeconds: 60
        failureThreshold: 10
  volumes:
  {{- if .Values.persistence.enabled }}
    {{- if .Values.persistence.pvname }}
      - name: {{ .Values.persistence.pvname }}
    {{ else }}
      - name: {{ include "oud-ds-rs.fullname" . }}-pv
    {{- end }}
        persistentVolumeClaim:
        {{- if .Values.persistence.pvcname }}
          claimName: {{ .Values.persistence.pvcname }}
        {{ else }}
          claimName: {{ include "oud-ds-rs.fullname" . }}-pvc
        {{- end }}
  {{- else }}
      - name: oud-storage
        emptyDir: {}
  {{- end }}
  {{- if .Values.configVolume.enabled }}
    {{- if .Values.configVolume.pvname }}
      - name: {{ .Values.configVolume.pvname }}
    {{ else }}
      - name: {{ include "oud-ds-rs.fullname" . }}-pv-config
    {{- end }}
        persistentVolumeClaim:
        {{- if .Values.configVolume.pvcname }}
          claimName: {{ .Values.configVolume.pvcname }}
        {{ else }}
          claimName: {{ include "oud-ds-rs.fullname" . }}-pvc-config
        {{- end }}
  {{- end }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

