#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
{{- $root := . -}}
{{- range $replicaIndex, $replicaN := until (.Values.replicaCount|int) }}
{{- $replicaIndx := (add $replicaIndex 1) -}}
#
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oud-ds-rs.fullname" $root }}-ldap-{{ $replicaIndx }}
  labels:
    {{- include "oud-ds-rs.labels" $root | nindent 4 }}
    oud/instance: {{ include "oud-ds-rs.fullname" $root }}-{{ $replicaIndx }}
  annotations:
spec:
  type: {{ $root.Values.service.type }}
  ports:
    - port: {{ $root.Values.oudPorts.ldap }}
      name: ldap
      targetPort: ldap
      protocol: TCP
    - port: {{ $root.Values.oudPorts.ldaps }}
      name: ldaps
      targetPort: ldaps
      protocol: TCP
  selector:
    {{- include "oud-ds-rs.selectorLabels" $root | nindent 4 }}
    oud/instance: {{ include "oud-ds-rs.fullname" $root }}-{{ $replicaIndx }}
---
{{- end }}
