#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oud-ds-rs.fullname" . }}-lbr-ldap
  labels:
    {{- include "oud-ds-rs.labels" . | nindent 4 }}
  annotations:
spec:
  type: {{ .Values.service.lbrtype }}
  ports:
    - port: {{ .Values.oudPorts.ldap }}
      name: ldap
      targetPort: ldap
      protocol: TCP
    - port: {{ .Values.oudPorts.ldaps }}
      name: ldaps
      targetPort: ldaps
      protocol: TCP
  selector:
    {{- include "oud-ds-rs.selectorLabels" . | nindent 4 }}
