#
# Copyright (c) 2024, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
{{ if not .Values.credentials.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "oracledb-fullname" . }}
  namespace: {{ include "oracledb-namespace" . }}
{{- include "oracledb-labels" . | indent 2 }}
stringData:
  username: {{ .Values.credentials.username  | quote }}
  password: {{ default (randAlphaNum 10) .Values.credentials.password | quote }}
---
{{ end }}
