# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# Default values for oracledb-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  repository: container-registry.oracle.com/database/operator
  pullPolicy: IfNotPresent
  tag: 1.0.0

# List of secrets to use to pull images from private registry
imagePullSecrets: []
