{{- if .Values.domain.serviceAccount.create -}}
# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "soa-suite.serviceAccountName" . }}
  labels:
    {{- include "soa-suite.labels" . | nindent 4 }}
  {{- with .Values.domain.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
