# Copyright (c) 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
image:
  name: traefik
  tag: 2.2.8
  pullPolicy: IfNotPresent
ingressRoute:
  dashboard:
    enabled: true
    annotations: {}
    labels: {}
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8000
    expose: true
    exposedPort: 30305
    nodePort: 30305
    protocol: TCP
  websecure:
    port: 8443
    expose: true
    exposedPort: 30443
    protocol: TCP
    nodePort: 30443