#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
---
apiVersion: v1
kind: Service
metadata:
  name: oud-dir-svc-1
  namespace: %NAMESPACE%
  labels:
    app: oud-dir-1
spec:
  ports:
  - port: 1444
    name: admin-ldaps
    targetPort: 1444
  - port: 1888
    name: admin-https
    targetPort: 1888
  - port: 1389
    name: ldap
    targetPort: 1389
  - port: 1636
    name: ldaps
    targetPort: 1636
  - port: 1080
    name: data-http
    targetPort: 1080
  - port: 1081
    name: data-https
    targetPort: 1081
  - port: 1898
    name: replication
    targetPort: 1898
  type: NodePort
  selector:
    app: oud-dir-1
---
apiVersion: v1
kind: Pod
metadata:
  name: oud-dir1
  namespace: %NAMESPACE%
  labels:
    app: oud-dir-1
spec:
  restartPolicy: OnFailure
  containers:
  - name: oudds
    image: %IMAGE%
    ports:
    - containerPort: 1444
    - containerPort: 1888
    - containerPort: 1389
    - containerPort: 1636
    - containerPort: 1080
    - containerPort: 1081
    - containerPort: 1898	
    env:
    - name: instanceType
      value: Directory
    - name: OUD_INSTANCE_NAME
      value: oud-dir1
    - name: hostname
      value: oud-dir-svc-1
    - name: baseDN
      value: dc=example1,dc=com
    - name: sampleData
      value: "100"
    - name: rootUserDN
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: rootUserDN
    - name: rootUserPassword
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: rootUserPassword
    - name: sleepBeforeConfig
      value: "3"
    volumeMounts:
    - mountPath: /u01/oracle/user_projects
      name: %PV_NAME%
    readinessProbe:
      tcpSocket:
        port: 1389
      initialDelaySeconds: 120
      periodSeconds: 30
    readinessProbe:
      tcpSocket:
        port: 1444
      initialDelaySeconds: 120
      periodSeconds: 30
    readinessProbe:
      tcpSocket:
        port: 1080
      initialDelaySeconds: 120
      periodSeconds: 30
    readinessProbe:
      exec:
        command:
          - "/u01/oracle/container-scripts/checkOUDInstance.sh"
      initialDelaySeconds: 120
      periodSeconds: 60
  imagePullSecrets:
  - name: regcred
  volumes:
       - name: %PV_NAME%
         persistentVolumeClaim:
           claimName: %PVC_NAME%
---
apiVersion: v1
kind: Service
metadata:
  name: oud-dir-svc-2
  namespace: %NAMESPACE%
  labels:
    app: oud-dir-2
spec:
  ports:
  - port: 1444
    name: admin-ldaps
    targetPort: 1444
  - port: 1888
    name: admin-https
    targetPort: 1888
  - port: 1389
    name: ldap
    targetPort: 1389
  - port: 1636
    name: ldaps
    targetPort: 1636
  - port: 1080
    name: data-http
    targetPort: 1080
  - port: 1081
    name: data-https
    targetPort: 1081
  - port: 1898
    name: replication
    targetPort: 1898
  type: NodePort
  selector:
    app: oud-dir-2
---
apiVersion: v1
kind: Pod
metadata:
  name: oud-dir2
  namespace: %NAMESPACE%
  labels:
    app: oud-dir-2
spec:
  restartPolicy: OnFailure
  containers:
  - name: oudds
    image: %IMAGE%
    ports:
    - containerPort: 1444
    - containerPort: 1888
    - containerPort: 1389
    - containerPort: 1636
    - containerPort: 1080
    - containerPort: 1081
    - containerPort: 1898	
    env:
    - name: instanceType
      value: Directory
    - name: OUD_INSTANCE_NAME
      value: oud-dir2
    - name: hostname
      value: oud-dir-svc-2
    - name: baseDN
      value: dc=example2,dc=com
    - name: sampleData
      value: "100"
    - name: rootUserDN
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: rootUserDN
    - name: rootUserPassword
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: rootUserPassword
    - name: sleepBeforeConfig
      value: "3"
    volumeMounts:
    - mountPath: /u01/oracle/user_projects
      name: %PV_NAME%
    readinessProbe:
      tcpSocket:
        port: 1389
      initialDelaySeconds: 120
      periodSeconds: 30
    readinessProbe:
      tcpSocket:
        port: 1444
      initialDelaySeconds: 120
      periodSeconds: 30
    readinessProbe:
      tcpSocket:
        port: 1080
      initialDelaySeconds: 120
      periodSeconds: 30
    readinessProbe:
      exec:
        command:
          - "/u01/oracle/container-scripts/checkOUDInstance.sh"
      initialDelaySeconds: 120
      periodSeconds: 60
  imagePullSecrets:
  - name: regcred
  volumes:
       - name: %PV_NAME%
         persistentVolumeClaim:
           claimName: %PVC_NAME%
