#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
---
apiVersion: v1
kind: Pod
metadata:
  name: oudpod1
  namespace: %NAMESPACE%
  labels:
    app: oud1
spec:
  restartPolicy: OnFailure
  hostname: oudpod1
  subdomain: oudsvc
  containers:
  - name: oudds1
    image: %IMAGE%
    ports:
    - containerPort: 1444
    - containerPort: 1888
    - containerPort: 1389
    - containerPort: 1636
    - containerPort: 1080
    - containerPort: 1081
    - containerPort: 1898	
    env:
    - name: instanceType
      value: Directory
    - name: OUD_INSTANCE_NAME
      value: oudpod1
    - name: hostname
      value: oudpod1
    - name: baseDN
      value: dc=example1,dc=com
    - name: sampleData
      value: "100"
    - name: rootUserDN
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: rootUserDN
    - name: rootUserPassword
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: rootUserPassword
    - name: sleepBeforeConfig
      value: "3"
    volumeMounts:
    - mountPath: /u01/oracle/user_projects
      name: %PV_NAME%
    readinessProbe:
      tcpSocket:
        port: 1389
      initialDelaySeconds: 120
      periodSeconds: 30
    readinessProbe:
      tcpSocket:
        port: 1444
      initialDelaySeconds: 120
      periodSeconds: 30
    readinessProbe:
      tcpSocket:
        port: 1080
      initialDelaySeconds: 120
      periodSeconds: 30
    readinessProbe:
      exec:
        command:
          - "/u01/oracle/container-scripts/checkOUDInstance.sh"
      initialDelaySeconds: 120
      periodSeconds: 60
  imagePullSecrets:
  - name: regcred
  volumes:
      - name: %PV_NAME%
        persistentVolumeClaim:
          claimName: %PVC_NAME%
