#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
---
apiVersion: v1
kind: Service
metadata:
  name: oud-dsrs-svc-1
  namespace: %NAMESPACE%
  labels:
    app: oud-ds-plus-rs-1
spec:
  ports:
  - port: 1444
    name: admin-ldaps
    targetPort: 1444
  - port: 1888
    name: admin-https
    targetPort: 1888
  - port: 1389
    name: ldap
    targetPort: 1389
  - port: 1636
    name: ldaps
    targetPort: 1636
  - port: 1080
    name: data-http
    targetPort: 1080
  - port: 1081
    name: data-https
    targetPort: 1081
  - port: 1898
    name: replication
    targetPort: 1898
  type: NodePort
  selector:
    app: oud-ds-plus-rs-1
---
apiVersion: v1
kind: Pod
metadata:
  name: ouddsrs1
  namespace: %NAMESPACE%
  labels:
    app: oud-ds-plus-rs-1
spec:
  restartPolicy: OnFailure
  hostname: oud-dsrs-svc-1
  containers:
  - name: ouddsrs
    image: %IMAGE%
    ports:
    - containerPort: 1444
    - containerPort: 1888
    - containerPort: 1389
    - containerPort: 1636
    - containerPort: 1080
    - containerPort: 1081
    - containerPort: 1898
    env:
    - name: sleepBeforeConfig
      value: "3"
    - name: instanceType
      value: AddDS2RS
    - name: OUD_INSTANCE_NAME
      value: ouddsrs1
    - name: hostname
      value: oud-dsrs-svc-1
    - name: baseDN
      value: dc=example2,dc=com
    - name: rootUserDN
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: rootUserDN
    - name: rootUserPassword
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: rootUserPassword
    - name: adminUID
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: adminUID
    - name: adminPassword 
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: adminPassword 
    - name: bindDN1
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: bindDN1
    - name: bindPassword1
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: bindPassword1
    - name: bindDN2
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: bindDN2
    - name: bindPassword2
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: bindPassword2
    - name: sourceHost
      value: oud-dir-svc-2
    - name: dsreplication_1
      value: verify --hostname ${sourceHost} --port ${adminConnectorPort} --baseDN ${baseDN} --serverToRemove ${hostname}:${adminConnectorPort}
    - name: dsreplication_2
      value: enable --host1 ${sourceHost} --port1 ${adminConnectorPort} --replicationPort1 ${replicationPort} --host2 ${hostname} --port2 ${adminConnectorPort} --replicationPort2 ${replicationPort} --baseDN ${baseDN}
    - name: dsreplication_3
      value: initialize --hostSource ${initializeFromHost} --portSource ${adminConnectorPort} --hostDestination ${hostname} --portDestination ${adminConnectorPort} --baseDN ${baseDN}
    - name: dsreplication_4
      value: verify --hostname ${hostname} --port ${adminConnectorPort} --baseDN ${baseDN}
    - name: dsreplication_5
      value: status --hostname ${hostname} --port ${adminConnectorPort} --baseDN ${baseDN} --dataToDisplay compat-view
    - name: post_dsreplication_dsconfig_1
      value: set-replication-domain-prop --domain-name ${baseDN} --set group-id:2
    - name: post_dsreplication_dsconfig_2
      value: set-replication-server-prop --set group-id:2
    volumeMounts:
    - mountPath: /u01/oracle/user_projects
      name: %PV_NAME%
    readinessProbe:
      tcpSocket:
        port: 1389
      initialDelaySeconds: 120
      periodSeconds: 30
    readinessProbe:
      tcpSocket:
        port: 1444
      initialDelaySeconds: 120
      periodSeconds: 30
    readinessProbe:
      tcpSocket:
        port: 1080
      initialDelaySeconds: 120
      periodSeconds: 30
    readinessProbe:
      exec:
        command:
          - "/u01/oracle/container-scripts/checkOUDInstance.sh"
      initialDelaySeconds: 120
      periodSeconds: 60
  imagePullSecrets:
  - name: regcred
  volumes:
       - name: %PV_NAME%
         persistentVolumeClaim:
           claimName: %PVC_NAME%
---
apiVersion: v1
kind: Service
metadata:
  name: oud-dsrs-svc-2
  namespace: %NAMESPACE%
  labels:
    app: oud-ds-plus-rs-2
spec:
  ports:
  - port: 1444
    name: admin-ldaps
    targetPort: 1444
  - port: 1888
    name: admin-https
    targetPort: 1888
  - port: 1389
    name: ldap
    targetPort: 1389
  - port: 1636
    name: ldaps
    targetPort: 1636
  - port: 1080
    name: data-http
    targetPort: 1080
  - port: 1081
    name: data-https
    targetPort: 1081
  - port: 1898
    name: replication
    targetPort: 1898
  type: NodePort
  selector:
    app: oud-ds-plus-rs-2
---
apiVersion: v1
kind: Pod
metadata:
  name: ouddsrs2
  namespace: %NAMESPACE%
  labels:
    app: oud-ds-plus-rs-2
spec:
  restartPolicy: OnFailure
  hostname: oud-dsrs-svc-2
  containers:
  - name: ouddsrs
    image: %IMAGE%
    ports:
    - containerPort: 1444
    - containerPort: 1888
    - containerPort: 1389
    - containerPort: 1636
    - containerPort: 1080
    - containerPort: 1081
    - containerPort: 1898
    env:
    - name: sleepBeforeConfig
      value: "300"
    - name: instanceType
      value: AddDS2RS
    - name: OUD_INSTANCE_NAME
      value: ouddsrs2
    - name: hostname
      value: oud-dsrs-svc-2
    - name: baseDN
      value: dc=example2,dc=com
    - name: rootUserDN
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: rootUserDN
    - name: rootUserPassword
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: rootUserPassword
    - name: adminUID
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: adminUID
    - name: adminPassword
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: adminPassword
    - name: bindDN1
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: bindDN1
    - name: bindPassword1
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: bindPassword1
    - name: bindDN2
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: bindDN2
    - name: bindPassword2
      valueFrom:
        secretKeyRef:
          name: %SECRET_NAME%
          key: bindPassword2
    - name: sourceHost
      value: oud-dir-svc-2
    - name: dsreplication_1
      value: verify --hostname ${sourceHost} --port ${adminConnectorPort} --baseDN ${baseDN} --serverToRemove ${hostname}:${adminConnectorPort}
    - name: dsreplication_2
      value: enable --host1 ${sourceHost} --port1 ${adminConnectorPort} --replicationPort1 ${replicationPort} --host2 ${hostname} --port2 ${adminConnectorPort} --replicationPort2 ${replicationPort} --baseDN ${baseDN}
    - name: dsreplication_3
      value: initialize --hostSource ${initializeFromHost} --portSource ${adminConnectorPort} --hostDestination ${hostname} --portDestination ${adminConnectorPort} --baseDN ${baseDN}
    - name: dsreplication_4
      value: verify --hostname ${hostname} --port ${adminConnectorPort} --baseDN ${baseDN}
    - name: dsreplication_5
      value: status --hostname ${hostname} --port ${adminConnectorPort} --baseDN ${baseDN} --dataToDisplay compat-view
    - name: post_dsreplication_dsconfig_1
      value: set-replication-domain-prop --domain-name ${baseDN} --set group-id:2
    - name: post_dsreplication_dsconfig_2
      value: set-replication-server-prop --set group-id:2
    volumeMounts:
    - mountPath: /u01/oracle/user_projects
      name: %PV_NAME%
    readinessProbe:
      tcpSocket:
        port: 1389
      initialDelaySeconds: 420
      periodSeconds: 30
    readinessProbe:
      tcpSocket:
        port: 1444
      initialDelaySeconds: 420
      periodSeconds: 30
    readinessProbe:
      tcpSocket:
        port: 1080
      initialDelaySeconds: 420
      periodSeconds: 30
    readinessProbe:
      exec:
        command:
          - "/u01/oracle/container-scripts/checkOUDInstance.sh"
      initialDelaySeconds: 420
      periodSeconds: 60
  imagePullSecrets:
  - name: regcred
  volumes:
       - name: %PV_NAME%
         persistentVolumeClaim:
           claimName: %PVC_NAME%
---
