# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# Default values for soa-suite.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""
kubernetesVersion: "1.23"

domain:
  # Set this flag to false to remove the domain before tear-down (default true)
  enabled: true
  # supported types: fmw, soa, osb, soaosb)
  type: soaosb

  # domainName should have no space, _ or -
  domainName: soainfra
  productionMode: true
  secureEnabled: false

  rootDir: /u01/oracle/user_projects
  scriptDir: /u01/weblogic

  # Weblogic user credentials for the domain
  # Either provide username and password, 
  # or provide the name of a secret containing username and password key/value pairs
  credentials: 
    secretName:
    username: weblogic
    password: Welcome1

  t3Channel:
    exposed: false
    port: 30012
    publicIp: "0.0.0.0"

  sslEnabled: false

  # 'jdbc' for persistence in database, otherwise null
  persistenceStore: jdbc

  # Logs
  logHomeEnabled: true
  logHome: /u01/oracle/user_projects/domains/logs
  includeServerOutInPodLog: true
  httpAccessLogInLogHome: true

  # serverStartPolicy legal values are "Never", "IfNeeded", or "AdminOnly"
  # This determines which WebLogic Servers the Operator will start up when it discovers this Domain
  # - "Never" will not start any server in the domain
  # - "AdminOnly" will start up only the administration server (no managed servers will be started)
  # - "IfNeeded" will start all non-clustered servers, including the administration server and clustered servers up to the replica count
  serverStartPolicy: IfNeeded
  javaOptions: "-Dweblogic.StdoutDebugEnabled=false"
  maxManagedServerCount: 5

  admin:
    name: AdminServer
    listenPort: 7001
    sslListenPort: 7002
    exposeNodePort: false
    nodePort: 30701
    administrationPort: 9002
    
  soaCluster:
    name: soa_cluster
    managedServers:
      count: 2
      name: soa_server
      listenPort: 7003
      sslListenPort: 7004
      administrationPort: 9004

  osbCluster:
    name: osb_cluster
    managedServers:
      count: 2
      name: osb_server
      listenPort: 8002
      sslListenPort: 8003
      administrationPort: 9007

  storage:
    capacity: 10Gi
    # The valid values are: 'Retain', 'Delete', and 'Recycle'
    reclaimPolicy: Retain
    # valid types are nfs or hostpath
    type: hostpath
    path: /scratch/k8s_dir
    #nfs:
    #  server: 10.0.10.34

  rcuSchema:
    prefix: SOA
    # profileType: supported values: SMALL(default), MED, LARGE
    profileType: SMALL
    # databaseType: supported values: ORACLE, EBR
    databaseType: EBR
    edition: 'ORA$BASE'
    credentials:
      # provide either the secretName of the secret containing 'username' and 'password' 
      # or provide 'username' and 'password' values
      # If a secret is specified it takes precedence over the plaintext entries
      secretName: 
      username: "SOA"
      password: "OraDB1_#OraDB1_#"


  image:
    repository: container-registry.oracle.com/middleware/soasuite_cpu
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 14.1.2.0.0

  # List of secrets to use to pull images from private registry
  imagePullSecrets: 

  # Service Account for this specific deployment
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

oracledb:
  # select enabled: true if the database should be provisioned
  provision: true
  namespaceOverride: default
  url: 
  #rcu-oracledb.soans.svc.cluster.local:1521/pdb.k8s
  # If url is not provided, deploy the DB and use the following params:
  # name of the Container DB
  oracle_sid: cdb
  # name of the Pluggable DB
  oracle_pdb: pdb
  persistence: null
  image: container-registry.oracle.com/database/enterprise:19.3.0.0
  credentials:
    # provide either the secretName of the secret containing 'username' and 'password' 
    # or provide 'username' and 'password' values
    secretName: 
    username: SYS
    password: "OraDB1_#OraDB1_#"
