# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# Default values for oracledb. Please check README for more information about below parameters

#
#nameOverride:

#
#namespaceOverride:

#
#fullnameOverride:

##This parameter changes the SID of the database. The default value is set to ORCLCDB.
oracle_sid: ORCLCDB

##This parameter modifies the name of the PDB. The default value is set to ORCLPDB1.
oracle_pdb: ORCLPDB1

## The Oracle Database SYS, SYSTEM and PDB_ADMIN password.
credentials:
   secretName:
   username: SYS
   password: "OraDB1_#OraDB1_#"

## The character set to use when creating the database. Defaults to AL32UTF8.
oracle_characterset: AL32UTF8

## The database edition (default: enterprise)
oracle_edition: enterprise

## Enable archive log mode when creating the database.
enable_archivelog: false

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
## Override 'persistence' to 'null' using '--set' option, if persistence is not desired (e.g. using the extended image with 'prebuiltdb' extension)
persistence:
  ## Oracle Database data Persistent Volume Storage Class, nfs or block
  storageClass: ""
  size: 100Gi
  accessMode: "ReadWriteOnce"
  volumeName: ""

## Deploy only on nodes in a particular availability domain, eg PHX-AD-1 on OCI
## Leave empty if there is no such requirement
availabilityDomain:

## Deploy multiple replicas for fast fail over
## If 'persistence' is 'null' then fast fail over will not happen even if replicas>1 (as no persistence)
replicas: 1

## deploy LoadBalancer service
loadBalService: false

## name of image
image: container-registry.oracle.com/database/enterprise:19.3.0.0

## image pull policy, IfNotPresent or Always
imagePullPolicy: Always

## container registry login/password
imagePullSecrets:
