# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "oracledb-operator.namespace" . }}/{{ include "oracledb-operator.fullname" . }}-serving-cert
  name: {{ include "oracledb-operator.fullname" . }}-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "oracledb-operator.fullname" . }}-webhook-service
      namespace: {{ include "oracledb-operator.namespace" . }}
      path: /mutate-database-oracle-com-v1alpha1-autonomousdatabase
  failurePolicy: Fail
  name: mautonomousdatabase.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "oracledb-operator.fullname" . }}-webhook-service
      namespace: {{ include "oracledb-operator.namespace" . }}
      path: /mutate-database-oracle-com-v1alpha1-autonomousdatabasebackup
  failurePolicy: Fail
  name: mautonomousdatabasebackup.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabasebackups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "oracledb-operator.fullname" . }}-webhook-service
      namespace: {{ include "oracledb-operator.namespace" . }}
      path: /mutate-database-oracle-com-v1alpha1-cdb
  failurePolicy: Fail
  name: mcdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "oracledb-operator.fullname" . }}-webhook-service
      namespace: {{ include "oracledb-operator.namespace" . }}
      path: /mutate-database-oracle-com-v1alpha1-dataguardbroker
  failurePolicy: Fail
  name: mdataguardbroker.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dataguardbrokers
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "oracledb-operator.fullname" . }}-webhook-service
      namespace: {{ include "oracledb-operator.namespace" . }}
      path: /mutate-database-oracle-com-v1alpha1-oraclerestdataservice
  failurePolicy: Fail
  name: moraclerestdataservice.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oraclerestdataservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "oracledb-operator.fullname" . }}-webhook-service
      namespace: {{ include "oracledb-operator.namespace" . }}
      path: /mutate-database-oracle-com-v1alpha1-pdb
  failurePolicy: Fail
  name: mpdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "oracledb-operator.fullname" . }}-webhook-service
      namespace: {{ include "oracledb-operator.namespace" . }}
      path: /mutate-database-oracle-com-v1alpha1-singleinstancedatabase
  failurePolicy: Fail
  name: msingleinstancedatabase.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - singleinstancedatabases
  sideEffects: None
