# Copyright (c) 2021, 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
{{- if eq .Values.type "TRAEFIK" }}
{{- if (eq .Values.sslType "NONSSL") }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-traefik
  namespace: {{ .Release.Namespace }}
  labels:
    weblogic.resourceVersion: domain-v2
  annotations:
    kubernetes.io/ingress.class: 'traefik'
spec:
  rules:
  - host: '{{ .Values.traefik.hostname }}'
    http:
      paths:
      - path: /console
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.adminServerPort }}
      - path: /em
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.adminServerPort }}
      - path: /wls-exporter
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.adminServerPort }}
      - path: /management
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.adminServerPort }}
      - path: /testconsole
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.adminServerPort }}
      - path: /cs
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /adfAuthentication
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /_ocsh
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /_dav
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /idcws
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /idcnativews
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /wsm-pm
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.ucmManagedServerPort }}
      - path: /ibr
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ibrClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.ibrManagedServerPort }}
      - path: /ibr/adfAuthentication
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ibrClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.ibrManagedServerPort }}
      - path: /weblogic/ready
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ucmClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.ucmManagedServerPort }}
      {{- if eq .Values.wlsDomain.ipmEnabled true }}
      - path: /imaging
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.ipmClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.ipmManagedServerPort }}
      {{- end }}
      {{- if eq .Values.wlsDomain.captureEnabled true }}
      - path: /dc-console
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.captureClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.captureManagedServerPort }}
      {{- end }}
      {{- if eq .Values.wlsDomain.captureEnabled true }}
      - path: /dc-client
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.captureClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.captureManagedServerPort }}
      {{- end }}
      {{- if eq .Values.wlsDomain.adfuiEnabled true }}
      - path: /wcc
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.wccadfClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.wccadfManagedServerPort }}
      {{- end }}

{{- end }}
{{- end }}

