# Copyright (c) 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# Default values for ingress-per-domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Load balancer type.  Supported values are: TRAEFIK, NGINX
type: TRAEFIK
#type: NGINX

# WLS domain as backend to the load balancer
wlsDomain:
  domainUID: wccinfra
  ucmClusterName: ucm_cluster
  ibrClusterName: ibr_cluster
  ucmManagedServerPort: 16200
  ibrManagedServerPort: 16250
  adminServerName: adminserver
  adminServerPort: 7001

# Traefik specific values
#traefik:
  # hostname used by host-routing
  # hostname: domain1.org

#nginx:
  # hostname used by host-routing
  # hostname: domain1.org



