# Copyright (c) 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: voyager-endtoendssl
  namespace: wcpns
  annotations:
    ingress.appscode.com/type: 'NodePort'
    ingress.appscode.com/stats: 'true'
    ingress.appscode.com/affinity: 'cookie'
    ingress.appscode.com/ssl-passthrough: "true"
spec:
  tls:
    - secretName: domain1-tls-cert
      hosts:
        - '*'
  rules:
    - host: '*'
      http:
        nodePort: '31443'
        paths:
          - path: /
            backend:
              serviceName: wcp-domain-cluster-wcp-cluster
              servicePort: '8889'
