# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# This is an example of creating an service account secret for Kubernetes 1.24+
#
apiVersion: v1 
kind: Secret 
type: kubernetes.io/service-account-token 
metadata: 
  name: oiri-service-account 
  namespace: <OIRINS> 
  annotations: 
    kubernetes.io/service-account.name: "oiri-service-account"
