# Copyright (c) 2026, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
{{- if eq .Values.type "TRAEFIK" }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-traefik-designconsole
  namespace: {{ .Release.Namespace }}
  labels:
    weblogic.resourceVersion: domain-v2
  annotations:
    kubernetes.io/ingress.class: 'traefik'
spec:
  entryPoints:
  {{- if (eq .Values.tls "SSL") }}
  - websecure
  {{- else }}
  - web
  {{- end }}
  routes:
  - match: PathPrefix(`/console`)
    kind: Rule
    {{- if (eq .Values.tls "SSL") }}
    middlewares: 
    - name: "{{ .Values.wlsDomain.domainUID }}-designconsole-proxy-ssl"
      namespace: "{{ .Release.Namespace }}"
    {{- end }}  
    services:
    - name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
      port: {{ .Values.wlsDomain.oimServerT3Port }}
      sticky:
        cookie:
          name: sticky-cookie
          httpOnly: true
{{- if (eq .Values.tls "SSL") }}
---
#Create Traefik Middleware custom resource for SSL Termination
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "{{ .Values.wlsDomain.domainUID }}-designconsole-proxy-ssl"
  namespace:  {{ .Release.Namespace }}
spec:
  headers:
    customRequestHeaders:
      X-Custom-Request-Header: ""
      X-Forwarded-For: ""
      WL-Proxy-Client-IP: ""
      WL-Proxy-SSL: ""
      X-Forwarded-Proto: "https"
      WL-Proxy-SSL: "true"
    sslRedirect: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  defaultCertificate:
    secretName:  {{ .Values.secretName}}
{{- end }}
{{- end }}
