#
# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl
#
#
{{- if .Values.elk.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oud-ds-rs.fullname" . }}-kibana
  labels:
    app: kibana
spec:
  replicas: {{ .Values.elk.kibana.kibanaReplicas }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: "{{ .Values.elk.kibana.image.repository }}:{{ .Values.elk.kibana.image.tag }}"
        resources:
{{ toYaml .Values.elk.elasticsearch.resources | indent 10 }}
        env:
          - name: ELASTICSEARCH_URL
            value: http://{{ include "oud-ds-rs.fullname" . }}-elasticsearch:{{ .Values.elk.elkPorts.rest }}
        ports:
        - containerPort: {{ .Values.elk.kibana.service.targetPort }}
    {{- with .Values.elk.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
    {{- end }}

{{- end }}
