#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
{{- if .Values.serviceAccount.create -}}
#
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "oud-ds-rs.fullname" . }}-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
{{- end -}}
