#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
{{- $root := . -}}
{{- range $replicaIndex, $replicaN := until (.Values.replicaCount|int) }}
{{- $replicaIndx := (add $replicaIndex 1) -}}
#
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oud-ds-rs.fullname" $root }}-http-{{ $replicaIndx }}
  labels:
    {{- include "oud-ds-rs.labels" $root | nindent 4 }}
    oud/instance: {{ include "oud-ds-rs.fullname" $root }}-{{ $replicaIndx }}
  annotations:
{{- if and ($root.Values.ingress.enabled) (eq $root.Values.ingress.type "voyager") (eq $root.Values.ingress.http.backendPort "https") }}
    ingress.appscode.com/backend-tls: "ssl verify none"
{{- end }}
spec:
  type: {{ $root.Values.service.type }}
  ports:
    - port: {{ $root.Values.oudPorts.http }}
      name: http
      targetPort: http
      protocol: TCP
    - port: {{ $root.Values.oudPorts.https }}
      name: https
      targetPort: https
      protocol: TCP
  selector:
    {{- include "oud-ds-rs.selectorLabels" $root | nindent 4 }}
    oud/instance: {{ include "oud-ds-rs.fullname" $root }}-{{ $replicaIndx }}
---
{{- end }}
