#
# Copyright (c) 2021, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
{{- if and (.Values.ingress.enabled) (eq .Values.ingress.type "nginx") -}}
{{- $fullName := include "oid.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress-nginx
  labels:
    {{- include "oid.labels" . | nindent 4 }}
  annotations:
{{- if (.Values.ingress.tlsEnabled) }}
  {{- with .Values.ingress.admin.nginxAnnotationsTLS }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- else }}
  {{- with .Values.ingress.admin.nginxAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
spec:
  tls:
{{- if (.Values.ingress.tlsSecret) }}
  - secretName: {{ .Values.ingress.tlsSecret }}
{{- else }}
  - secretName: {{ include "oid.fullname" . }}-tls-cert
{{- end }}
    hosts:
    - {{ include "oid.fullname" . }}
  rules:
  - http:
      paths:
      - path: /odsm
        backend:
          serviceName: {{ include "oid.fullname" . }}host1
          servicePort: {{ .Values.ingress.http.backendPort }}
      - path: /console
        backend:
          serviceName: {{ include "oid.fullname" . }}host1
          servicePort: {{ .Values.ingress.http.backendPort }}
{{- end }}
