#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl
#
#
{{- if .Values.elk.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "oudsm.fullname" . }}-elasticsearch
  labels:
    app: {{ include "oudsm.fullname" . }}-elasticsearch
spec:
  selector:
    app: {{ include "oudsm.fullname" . }}-elasticsearch
  clusterIP: None
  ports:
    - port: {{ .Values.elk.elkPorts.rest}}
      name: rest
    - port: {{ .Values.elk.elkPorts.internode}}
      name: inter-node
{{- end }}
---
{{- if .Values.elk.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace:
  name: {{ include "oudsm.fullname" . }}-kibana
  labels:
    app: kibana
spec:
  type: {{ .Values.elk.kibana.service.type }}
  ports:
  - port: {{ .Values.elk.kibana.service.targetPort }}
    targetPort: {{ .Values.elk.kibana.service.targetPort }}
    nodePort: {{ .Values.elk.kibana.service.nodePort }}
  selector:
    app: kibana
{{- end }}
---

{{- if .Values.elk.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "oudsm.fullname" . }}-logstash-service
spec:
  type: {{ .Values.elk.logstash.service.type }}
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: {{ .Values.elk.logstash.service.targetPort }}
    targetPort: {{ .Values.elk.logstash.service.targetPort }}
    name: logstash
{{- end }}
