#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
{{- $root := . -}}
{{- if and (.Values.ingress.enabled) (eq .Values.ingress.type "voyager") -}}
{{- $fullName := include "oudsm.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $svcSslPort := .Values.service.sslPort -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
# apiVersion: networking.k8s.io/v1beta1
apiVersion: voyager.appscode.com/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress-voyager
  labels:
    {{- include "oudsm.labels" . | nindent 4 }}
  annotations:
{{- if (.Values.ingress.tlsEnabled) }}
  {{- with .Values.ingress.voyagerAnnotationsTLS }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- else }}
  {{- with .Values.ingress.voyagerAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
spec:
  frontendRules:
  - port: {{ .Values.ingress.voyagerHttpsPort }}
    rules:
    - http-request set-header WL-Proxy-SSL true
{{- if (.Values.ingress.voyagerExternalIPs) }}
  externalIPs:
{{- with .Values.ingress.voyagerExternalIPs }}
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
  tls:
{{- if (.Values.ingress.tlsSecret) }}
  - secretName: {{ .Values.ingress.tlsSecret }}
{{- else }}
  - secretName: {{ include "oudsm.fullname" . }}-tls-cert
{{- end }}
    hosts:
    -  '*'
{{- if (.Values.ingress.host) }}
  {{- if (.Values.ingress.domain) }}
    - {{ .Values.ingress.host }}.{{ .Values.ingress.domain }}
  {{ else }}
    - {{ .Values.ingress.host }}
  {{- end }}
{{ else }}
    - {{ include "oudsm.fullname" . }}
{{- end }}
{{- range $replicaIndex, $replicaN := until (.Values.replicaCount|int) }}
{{- $replicaIndx := (add $replicaIndex 1) }}
{{- if ($root.Values.ingress.host) }}
  {{- if ($root.Values.ingress.domain) }}
    - {{ $root.Values.ingress.host }}-{{ $replicaIndx }}.{{ $root.Values.ingress.domain }}
  {{ else }}
    - {{ $root.Values.ingress.host }}-{{ $replicaIndx }}
  {{- end }}
{{ else }}
    - {{ include "oudsm.fullname" $root }}-{{ $replicaIndx }}
{{- end }}
{{- end }}
  rules:
{{- range $replicaIndex, $replicaN := until (.Values.replicaCount|int) }}
{{- $replicaIndx := (add $replicaIndex 1) }}
{{- if ($root.Values.ingress.host) }}
  {{- if ($root.Values.ingress.domain) }}
  - host: {{ $root.Values.ingress.host }}-{{ $replicaIndx }}.{{ $root.Values.ingress.domain }}
  {{ else }}
  - host: {{ $root.Values.ingress.host }}-{{ $replicaIndx }}
  {{- end }}
{{ else }}
  - host: {{ include "oudsm.fullname" $root }}-{{ $replicaIndx }}
{{- end }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "oudsm.fullname" $root }}-{{ $replicaIndx }}
          servicePort: {{ $root.Values.ingress.backendPort }}
{{- end }}
{{- if (.Values.ingress.host) }}
  {{- if (.Values.ingress.domain) }}
  - host: {{ .Values.ingress.host }}.{{ .Values.ingress.domain }}
  {{ else }}
  - host: {{ .Values.ingress.host }}
  {{- end }}
{{ else }}
  - host: '*'
{{- end }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "oudsm.fullname" . }}-lbr
          servicePort: {{ .Values.ingress.backendPort }}
      - path: /oudsm
        backend:
          serviceName: {{ include "oudsm.fullname" . }}-lbr
          servicePort: {{ .Values.ingress.backendPort }}
      - path: /console
        backend:
          serviceName: {{ include "oudsm.fullname" . }}-lbr
          servicePort: {{ .Values.ingress.backendPort }}
{{- end }}
