# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if eq .Values.type "NGINX" }}
---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: access-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    weblogic.resourceVersion: domain-v2
{{- if eq .Values.sslType "SSL" }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "2000k"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-access-log: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_input_headers "X-Forwarded-Proto: https";
      more_clear_input_headers "WL-Proxy-Client-IP" "WL-Proxy-SSL";
      more_set_input_headers "WL-Proxy-SSL: true";
    nginx.ingress.kubernetes.io/ingress.allow-http: "false"
{{- end }}
spec:
  rules:
    {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
    - http:
        paths:
        - path: /console
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              port:
                number: {{ .Values.wlsDomain.adminServerPort }}
        - path: /rreg/rreg
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              port:
                number: {{ .Values.wlsDomain.adminServerPort }}
        - path: /em
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              port:
                number: {{ .Values.wlsDomain.adminServerPort }}
        - path: /oamconsole
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              port:
                number: {{ .Values.wlsDomain.adminServerPort }}
        - path: /dms
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'   
              port:
                number: {{ .Values.wlsDomain.adminServerPort }}
        - path: /oam/services/rest
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              port:
                number: {{ .Values.wlsDomain.adminServerPort }}
        - path: /iam/admin/config
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              port:
                number: {{ .Values.wlsDomain.adminServerPort }}
        - path: /iam/admin/diag
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              port:
                number: {{ .Values.wlsDomain.adminServerPort }}
        - path: /iam/access
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oamClusterName | lower | replace "_" "-" }}'
              port:
                number: {{ .Values.wlsDomain.oamManagedServerPort }}
        - path: /oam/admin/api
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}' 
              port:
                number: {{ .Values.wlsDomain.adminServerPort }}
        - path: /oam/services/rest/access/api
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oamClusterName | lower | replace "_" "-" }}'
              port:
                number: {{ .Values.wlsDomain.oamManagedServerPort }}
        - path: /access
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.policyClusterName | lower | replace "_" "-" }}'
              port:
                number: {{ .Values.wlsDomain.policyManagedServerPort }}
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oamClusterName | lower | replace "_" "-" }}'
              port:
                number: {{ .Values.wlsDomain.oamManagedServerPort }}
{{- else }}
    - http:
        paths:
        - path: /console
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path: /rreg/rreg
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path: /em
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path: /oamconsole
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path: /dms
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path: /oam/services/rest
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path: /iam/admin/config
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path: /iam/admin/diag
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path: /iam/access
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oamClusterName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.oamManagedServerPort }}
        - path: /oam/admin/api
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path: /oam/services/rest/access/api
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oamClusterName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.oamManagedServerPort }}
        - path: /access
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.policyClusterName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.policyManagedServerPort }}
        - path: /
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oamClusterName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.oamManagedServerPort }}

{{- end }}
{{- end }}
