# Copyright (c) 2021, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "oid.fullname" . }}host1
  labels:
    {{- include "oid.labels" . | nindent 4 }}
    oid/instance: {{ include "oid.fullname" . }}host1
spec:
  restartPolicy: {{ .Values.restartPolicyName }}
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceAccountName: {{ include "oid.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  containers:
    - name: {{ .Chart.Name }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - name: ldap
          containerPort: {{ .Values.oidPorts.ldap }}
          protocol: TCP
        - name: ldaps
          containerPort: {{ .Values.oidPorts.ldaps }}
          protocol: TCP
        - name: http
          containerPort: {{ .Values.odsmPorts.http }}
          protocol: TCP
        - name: https
          containerPort: {{ .Values.odsmPorts.https }}
          protocol: TCP
      {{- if .Values.baseOID.envVarsConfigMap }}
      envFrom:
      - configMapRef:
          name: {{ .Values.baseOID.envVarsConfigMap }}
      {{- end }}
      env:
        {{- with .Values.baseOID.envVars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: INSTANCE_TYPE
          value: PRIMARY
        - name: sleepBeforeConfig
          value: "180"
        - name: INSTANCE_NAME
          value: oid1
        - name: ADMIN_LISTEN_HOST
          value: {{ include "oid.fullname" . }}host1
        - name: REALM_DN
          value: {{ .Values.oidConfig.realmDN }}
        - name: CONNECTION_STRING
          value: {{ .Values.oidConfig.rcuDatabaseURL }}
        - name: LDAP_PORT
          value: {{ .Values.oidPorts.ldap|quote }}
        - name: LDAPS_PORT
          value: {{ .Values.oidPorts.ldaps|quote }}
        - name: ADMIN_LISTEN_PORT
          value: {{ .Values.odsmPorts.http|quote }}
        - name: ADMIN_LISTEN_SSL_PORT
          value: {{ .Values.odsmPorts.https|quote }}
        - name: DOMAIN_NAME
          value: oid_domain
        - name: DOMAIN_HOME
          value: {{ .Values.oidConfig.domainHome }}
        - name: RCUPREFIX
          value: {{ .Values.oidConfig.rcuSchemaPrefix }}
        {{- if .Values.secret.enabled }}
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
                {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              key: adminUser
                {{- else }}
              name:  {{ include "oid.fullname" . }}-creds
              key: adminUser
                {{- end }}
        {{- else }} 
        - name: ADMIN_USER
          value: {{ .Values.odsm.adminUser }}
        {{- end }}
        {{- if .Values.secret.enabled }}
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              key: adminPassword
              {{- else }}
              name:  {{ include "oid.fullname" . }}-creds
              key: adminPassword
              {{- end }}
        {{- else }}
        - name: ADMIN_PASSWORD
          value: {{ .Values.odsm.adminPassword }}
        {{- end }}
       {{- if .Values.secret.enabled }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              key: dbUser
              {{- else }}
              name:  {{ include "oid.fullname" . }}-creds
              key: dbUser
              {{- end }}
        {{- else }}
        - name: DB_USER
          value: {{ .Values.oidConfig.dbUser }}
        {{- end }}
       {{- if .Values.secret.enabled }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              key: dbPassword
              {{- else }}
              name:  {{ include "oid.fullname" . }}-creds
              key: dbPassword
              {{- end }}
        {{- else }}
        - name: DB_PASSWORD
          value: {{ .Values.oidConfig.dbPassword }}
        {{- end }}
       {{- if .Values.secret.enabled }}
        - name: DB_SCHEMA_PASSWORD
          valueFrom:
            secretKeyRef:
              {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              key: dbschemaPassword
              {{- else }}
              name:  {{ include "oid.fullname" . }}-creds
              key: dbschemaPassword
              {{- end }}
        {{- else }}
        - name: DB_SCHEMA_PASSWORD
          value: {{ .Values.oidConfig.dbschemaPassword }}
        {{- end }}
       {{- if .Values.secret.enabled }}
        - name: ORCL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              key: orcladminPassword
              {{- else }}
              name:  {{ include "oid.fullname" . }}-creds
              key: orcladminPassword
              {{- end }}
        {{- else }}
        - name: ORCL_ADMIN_PASSWORD
          value: {{ .Values.oidConfig.orcladminPassword }}
        {{- end }}
       {{- if .Values.secret.enabled }}
        - name: SSL_WALLET_PASSWORD
          valueFrom:
            secretKeyRef:
              {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              key: sslwalletPassword
              {{- else }}
              name:  {{ include "oid.fullname" . }}-creds
              key: sslwalletPassword
              {{- end }}
        {{- else }}
        - name: SSL_WALLET_PASSWORD
          value: {{ .Values.oidConfig.sslwalletPassword }}
        {{- end }}
        - name: ldapPort
          value: {{ .Values.oidPorts.ldap | quote }}
        - name: ldapsPort
          value: {{ .Values.oidPorts.ldaps | quote }}
        - name: httpPort
          value: {{ .Values.odsmPorts.http | quote }}
        - name: httpsPort
          value: {{ .Values.odsmPorts.https | quote }}
      volumeMounts:
        - mountPath: /u01/oracle/user_projects
        {{- if .Values.persistence.enabled }}
          {{- if .Values.persistence.pvname }}
          name: {{ .Values.persistence.pvname }}
          {{ else }}
          name: {{ include "oid.fullname" . }}-pv
          {{- end }}
        {{- else }}
          name: oid-storage
          subPath: user_projects
        {{- end }}
      readinessProbe:
        tcpSocket:
          port: {{ .Values.oidPorts.ldap | quote }}
        initialDelaySeconds: {{ (.Values.deploymentConfig.adminProbeInitialDelay|int) }}
        timeoutSeconds: 15
        periodSeconds: 60
        failureThreshold: 15
      readinessProbe:
        tcpSocket:
          port: {{ .Values.oidPorts.ldaps | quote }}
        initialDelaySeconds: {{ (.Values.deploymentConfig.adminProbeInitialDelay|int) }}
        timeoutSeconds: 15
        periodSeconds: 60
        failureThreshold: 15
      readinessProbe:
        exec:
          command:
            - "/u01/oracle/dockertools/healthcheck_status.sh"
        initialDelaySeconds: {{ (.Values.deploymentConfig.adminProbeInitialDelay|int) }}
        timeoutSeconds: 30
        periodSeconds: 60
        failureThreshold: 15
  volumes:
  {{- if .Values.persistence.enabled }}
    {{- if .Values.persistence.pvname }}
      - name: {{ .Values.persistence.pvname }}
    {{ else }}
      - name: {{ include "oid.fullname" . }}-pv
    {{- end }}
        persistentVolumeClaim:
        {{- if .Values.persistence.pvcname }}
          claimName: {{ .Values.persistence.pvcname }}
        {{ else }}
          claimName: {{ include "oid.fullname" . }}-pvc
        {{- end }}
  {{- else }}
      - name: oid-storage
        emptyDir: {}
  {{- end }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

