#
# Copyright (c) 2021, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
{{- $defUserDNb64 := "Y249RGlyZWN0b3J5IE1hbmFnZXI=" -}}
{{- $randUserRootPwdStr := ( randAlphaNum 10 | toString ) -}}
{{- if and .Values.secret.enabled (not .Values.secret.name) }}
#
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oid.fullname" . }}-creds
  labels:
    {{- include "oid.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
data:
  {{- if .Values.odsm.adminUser }}
  adminUser: {{ .Values.odsm.adminUser | b64enc }}
  {{- else }}
  adminUser: {{ $defUserDNb64 }}
  {{- end }}
  {{- if .Values.odsm.adminPassword }}
  adminPassword: {{ .Values.odsm.adminPassword | b64enc }}
  {{- else }}
  adminPassword: {{ $randUserRootPwdStr | b64enc }}
  {{- end }}
  {{- if .Values.oidConfig.dbUser }}
  dbUser: {{ .Values.oidConfig.dbUser | b64enc }}
  {{- else }}
  dbUser: c3lz
  {{- end }}
  {{- if .Values.oidConfig.dbPassword }}
  dbPassword: {{ .Values.oidConfig.dbPassword | b64enc }}
  {{- end }}
  {{- if .Values.oidConfig.dbschemaPassword }}
  dbschemaPassword: {{.Values.oidConfig.dbschemaPassword | b64enc }}
  {{- end }}
  {{- if .Values.oidConfig.orcladminPassword }}
  orcladminPassword: {{.Values.oidConfig.orcladminPassword | b64enc }}
  {{- end }}
  {{- if .Values.oidConfig.sslwalletPassword }}
  sslwalletPassword: {{.Values.oidConfig.sslwalletPassword | b64enc }}
  {{- end }}
{{- end }}
