#
# Copyright (c) 2021, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oid.fullname" . }}-lbr-ldap
  labels:
    {{- include "oid.labels" . | nindent 4 }}
  annotations:
spec:
  type: {{ .Values.service.lbrtype }}
  ports:
    - port: {{ .Values.oidPorts.ldap }}
      name: ldap
      targetPort: {{ .Values.oidPorts.ldap }}
      protocol: TCP
    - port: {{ .Values.oidPorts.ldaps }}
      name: ldaps
      targetPort: {{ .Values.oidPorts.ldaps }}
      protocol: TCP
  selector:
    {{- include "oid.selectorLabels" . | nindent 4 }}
