#
# Copyright (c) 2021, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "oid.fullname" . }}-tls-cert
data:
{{ ( include "oid.gen-selfsigned-certs" . ) | indent 2 }}

