#
# Copyright (c) 2023, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl
#
#
{{- if .Values.configVolume.enabled }}
{{ if .Values.configVolume.storageClassCreate }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: {{ .Values.configVolume.storageClass }}
    annotations:
      storageclass.kubernetes.io/is-default-class: {{ .Values.configVolume.storageClassDefault | quote }}
provisioner: {{ .Values.configVolume.provisioner }}
{{ end }}
{{- end }}
