#
# Copyright (c) 2022, 2023, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl
#

--- 
{{- if .Values.cronJob.enabled }}
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata: 
  name: oud-pod-cron-job
  namespace: {{ .Release.Namespace }}
spec: 
  jobTemplate: 
    spec: 
      template: 
        spec:
        {{- with .Values.cronJob.imagePullSecrets }}
          imagePullSecrets:
{{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ include "oud-ds-rs.serviceAccountName" . }}-job
          containers: 
            - name: cron-kubectl 
              command: 
                - "/bin/bash"
                - "-c"
                - "for i in `kubectl get nodes --no-headers | awk '{if ($2 == \"NotReady\") print $1}'`;do for j in `kubectl get pods -n {{ .Release.Namespace }}  --field-selector spec.nodeName=$i |awk '{if ($3 == \"Terminating\") print $1}'`;do kubectl delete pods -n {{ .Release.Namespace }} $j --force;done;done"
              image: "{{ .Values.cronJob.kubectlImage.repository }}:{{ .Values.cronJob.kubectlImage.tag }}"
              imagePullPolicy: {{ .Values.cronJob.kubectlImage.pullPolicy }}
          restartPolicy: OnFailure
  schedule: {{ .Values.cronJob.schedule }}
{{- end }}
