#
# Copyright (c) 2020, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
{{- if .Values.serviceAccount.create -}}
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "oud-ds-rs.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "oud-ds-rs.fullname" . }}-role
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "oud-ds-rs.serviceAccountName" . }}
{{- end }}
