#
# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#
{{- if (.Values.service.allSvcEnabled) -}}
{{- $root := . -}}
{{- range $replicaN := until (.Values.replicaCount| int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oud-ds-rs.fullname" $root }}-all-{{ $replicaN }}
  labels:
    {{- include "oud-ds-rs.labels" $root | nindent 4 }}
  annotations:
spec:
  type: {{ $root.Values.service.allSvcType }}
  ports:
    - port: {{ $root.Values.oudPorts.adminldaps }}
      name: adminldaps
      targetPort: adminldaps
      protocol: TCP
    - port: {{ $root.Values.oudPorts.adminhttps }}
      name: adminhttps
      targetPort: adminhttps
      protocol: TCP
    - port: {{ $root.Values.oudPorts.replication }}
      name: replication
      targetPort: replication
      protocol: TCP
    - port: {{ $root.Values.oudPorts.http }}
      name: http
      targetPort: http
      protocol: TCP
    - port: {{ $root.Values.oudPorts.https }}
      name: https
      targetPort: https
      protocol: TCP
    - port: {{ $root.Values.oudPorts.ldap }}
      name: ldap
      targetPort: ldap
      protocol: TCP
    - port: {{ $root.Values.oudPorts.ldaps }}
      name: ldaps
      targetPort: ldaps
      protocol: TCP
  selector:
    {{- include "oud-ds-rs.selectorLabels" $root | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "oud-ds-rs.fullname" $root }}-{{ $replicaN }}
---
{{- end }}
{{- end }}
