# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.domain.domainName }}-traefik
  labels:
    weblogic.resourceVersion: domain-v2
  annotations:
    kubernetes.io/ingress.class: traefik
{{- if .Values.ingress.tls }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: wcsites-ns-wls-proxy-ssl@kubernetescrd
{{- end }}
spec:
  rules:
  - host: ''
    http:
      paths:
      - path: /console
        backend:
          serviceName: '{{ .Values.domain.domainName }}-{{ .Values.domain.admin.name | lower | replace "_" "-" }}'
          servicePort: {{ .Values.domain.admin.listenPort }}
      - path: /em
        backend:
          serviceName: '{{ .Values.domain.domainName }}-{{ .Values.domain.admin.name | lower | replace "_" "-" }}'
          servicePort: {{ .Values.domain.admin.listenPort }}
      - path: /weblogic/ready
        backend:
          serviceName: '{{ .Values.domain.domainName }}-{{ .Values.domain.admin.name | lower | replace "_" "-" }}'
          servicePort: {{ .Values.domain.admin.listenPort }}
      - path: /sites
        backend:
          serviceName: '{{ .Values.domain.domainName }}-cluster-{{ .Values.domain.wcsCluster.name | lower | replace "_" "-" }}'
          servicePort: {{ .Values.domain.wcsCluster.managedServers.listenPort  }}
      - path: /cas
        backend:
          serviceName: '{{ .Values.domain.domainName }}-cluster-{{ .Values.domain.wcsCluster.name | lower | replace "_" "-" }}'
          servicePort: {{ .Values.domain.wcsCluster.managedServers.listenPort  }}
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - '{{ .Values.ingress.dnsname }}'
    secretName: {{ .Values.domain.domainName }}-tls-cert
{{- end }}

