# Copyright (c) 2020, 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
{{- if eq .Values.type "NGINX" }}
{{- if (eq .Values.sslType "NONSSL") }}
{{- if not .Values.hostName.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-nginx
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/affinity: 'cookie'
    nginx.ingress.kubernetes.io/session-cookie-name: 'sticky'
    nginx.ingress.kubernetes.io/affinity-mode: 'persistent'
    nginx.ingress.kubernetes.io/enable-access-log: 'false'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '{{ .Values.nginx.nginxTimeOut }}'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '{{ .Values.nginx.nginxTimeOut }}'
spec:
  ingressClassName: nginx
  rules:
  - host:
    http:
      paths:
      - path: /console
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.adminServerPort }}
      - path: /consolehelp
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.adminServerPort }}
      - path: /em
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.adminServerPort }}
      - path: /management
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.adminServerPort }}              
      - path: /ws_utc
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.soaClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.soaManagedServerPort }}
      - path: /soa
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.soaClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.soaManagedServerPort }}
      - path: /integration
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.soaClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.soaManagedServerPort }}
      - path: /soa-infra
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.soaClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.soaManagedServerPort }}
      - path: /identity
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /admin
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /dms
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.adminServerPort }}
      - path: /oim
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /sysadmin
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /workflowservice
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /callbackResponseService
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /spml-xsd
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /HTTPClnt
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /reqsvc
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /iam
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /provisioning-callback
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /CertificationCallbackService
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /ucs
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /FacadeWebApp
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /OIGUI
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
      - path: /weblogic
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.oimClusterName | lower | replace "_" "-" }}'
            port:
              number: {{ .Values.wlsDomain.oimManagedServerPort }}
     
{{- end }}
{{- end }}
{{- end }}

