# Copyright (c) 2020, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: v1
kind: Service
metadata:
  name: oamdb
  labels:
    app: oamdb
  namespace: accessns
spec:
  ports:
  - port: 1521
    name: server-port
  - port: 5500
    name: em-port
  clusterIP: None
  selector:
    app: oamdb
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: oamdb
  namespace: accessns
spec:
  serviceName: "oamdb"
  replicas: 1
  template:
    metadata:
      labels:
        app: oamdb
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: oamdb
        image: oracle/database:12.2.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1521
          name: server-port
        - containerPort: 5500
          name: em-port
        env:
        - name: DB_SID
          value: oamdb
        - name: DB_PDB
          value: oampdb
        - name: DB_DOMAIN
          value: my.domain.com
        - name: DB_BUNDLE
          value: basic
        readinessProbe:
          exec:
            command:
            - grep
            - "Done ! The database is ready for use ."
            - "/home/oracle/setup/log/setupDB.log"
          initialDelaySeconds: 300
          periodSeconds: 5
        volumeMounts:
        - mountPath: /ORCL
          name: oamdb-storage
      volumes:
      - name: oamdb-storage
        persistentVolumeClaim:
          claimName: oamdb-pvc
